language: android

sudo: false

notifications:
  email: false

jdk:
  - oraclejdk8
  
android:
  components:
        -build-tools-25.0.2
        -android-25

        - extra-android-m2repository
        - extra-android-support

        - platform-tools
        - tools

        - add-on
        - extra

before_install:     
 - chmod +x gradlew

script:
     - ./gradlew assembleRelease
