language: android
android:
  components:
        -build-tools-25.0.2
        -android-25
        - add-on
        - extra
        - platform-tools
        - tools


script: ./gradlew build bintrayUpload -PbintrayUser=naivor -PbintrayKey=0cbed428ebc41a02e05c1cae1e4e78a6707da450 -PdryRun=false 
