language: android
android:
  components:
        -build-tools-25.0.2
        -android-25

        - extra-android-m2repository
        - extra-android-support

        - platform-tools
        - tools

        - add-on
        - extra


script:
    - "./gradlew build"
