language:android
jdk: oraclejdk8
sudo: false

android:
    components:
	-build-tools-25.0.2
	-android-25
 	- add-on
    	- extra
	- platform-tools
    	- tools


script: ./gradlew build bintrayUpload 
